### ISSUE TITLE
posts not saving, redirecting to "sorry we can't find that"

### ISSUE THREAD

**Issue by ricleichtung** [udbhav/adhoc#61]

**Comment by udbhav** [comment]
Could you give me a little more detail, which link gives you the 404, the admin page link, or the actual post?  

As an example let's use that Blues Control post you've been working on.  http://adhoc.fm/admin/blog/post/20/ works, but when you click view on site and go to http://adhoc.fm/post/blues-control-iron-pigs/ that gives you a 404, which it should since it's not published yet.  Clicking the preview button on the top right takes you http://adhoc.fm/preview/20/ which will show you what it will look like when it's published.

I think it might be confusing, so maybe I'll make it so the view on site button isn't even available if it's not published yet.  Would that be helpful?
